TEAM_ABBREVIATIONS = {
    "Arizona Cardinals": "ARI",
    "Cardinals": "ARI",
    "Arizona": "ARI",
    "Atlanta Falcons": "ATL",
    "Falcons": "ATL",
    "Atlanta": "ATL",
    "Baltimore Ravens": "BAL",
    "Ravens": "BAL",
    "Baltimore": "BAL",
    "Buffalo Bills": "BUF",
    "Bills": "BUF",
    "Buffalo": "BUF",
    "Carolina Panthers": "CAR",
    "Panthers": "CAR",
    "Carolina": "CAR",
    "Chicago Bears": "CHI",
    "Bears": "CHI",
    "Chicago": "CHI",
    "Cincinnati Bengals": "CIN",
    "Bengals": "CIN",
    "Cincinnati": "CIN",
    "Cleveland Browns": "CLE",
    "Browns": "CLE",
    "Cleveland": "CLE",
    "Dallas Cowboys": "DAL",
    "Cowboys": "DAL",
    "Dallas": "DAL",
    "Denver Broncos": "DEN",
    "Broncos": "DEN",
    "Denver": "DEN",
    "Detroit Lions": "DET",
    "Lions": "DET",
    "Detroit": "DET",
    "Green Bay Packers": "GB",
    "Packers": "GB",
    "Green Bay": "GB",
    "Houston Texans": "HOU",
    "Texans": "HOU",
    "Houston": "HOU",
    "Indianapolis Colts": "IND",
    "Colts": "IND",
    "Indianapolis": "IND",
    "Jacksonville Jaguars": "JAX",
    "Jaguars": "JAX",
    "Jacksonville": "JAX",
    "Kansas City Chiefs": "KC",
    "Chiefs": "KC",
    "Kansas City": "KC",
    "Las Vegas Raiders": "LV",
    "Raiders": "LV",
    "Las Vegas": "LV",
    "Los Angeles Chargers": "LAC",
    "Chargers": "LAC",
    "LA Chargers": "LAC",
    "Los Angeles Rams": "LAR",
    "Rams": "LAR",
    "LA Rams": "LAR",
    "Miami Dolphins": "MIA",
    "Dolphins": "MIA",
    "Miami": "MIA",
    "Minnesota Vikings": "MIN",
    "Vikings": "MIN",
    "Minnesota": "MIN",
    "New England Patriots": "NE",
    "Patriots": "NE",
    "New England": "NE",
    "New Orleans Saints": "NO",
    "Saints": "NO",
    "New Orleans": "NO",
    "New York Giants": "NYG",
    "Giants": "NYG",
    "NY Giants": "NYG",
    "New York Jets": "NYJ",
    "Jets": "NYJ",
    "NY Jets": "NYJ",
    "Philadelphia Eagles": "PHI",
    "Eagles": "PHI",
    "Philadelphia": "PHI",
    "Pittsburgh Steelers": "PIT",
    "Steelers": "PIT",
    "Pittsburgh": "PIT",
    "San Francisco 49ers": "SF",
    "49ers": "SF",
    "San Francisco": "SF",
    "Seattle Seahawks": "SEA",
    "Seahawks": "SEA",
    "Seattle": "SEA",
    "Tampa Bay Buccaneers": "TB",
    "Buccaneers": "TB",
    "Tampa Bay": "TB",
    "Tennessee Titans": "TEN",
    "Titans": "TEN",
    "Tennessee": "TEN",
    "Washington Commanders": "WAS",
    "Commanders": "WAS",
    "Washington": "WAS"
}

def get_team_abbreviation(team_name):
    return TEAM_ABBREVIATIONS.get(team_name, team_name)
